### PR TITLE
feat: Make the command server shortcut configurable

### PR DESCRIPTION
**Pull request by fidgetingbits**

### CODE REVIEW

**Comment by saidelike** [comment]
Sounds good. We also need to discuss what default shortcut we want for people to use on the different platform, see https://github.com/hands-free-vim/neovim-talon/issues/20

then I guess we need to set the setting for the different platforms by default in neovim-talon?

**Comment by fidgetingbits** [comment]
Me changing this is pending on if ctrl-` works on Windows, in which case we can have a single default, otherwise I will set the default based on the platform. See https://github.com/saidelike/cursorless/pull/2

**Comment by saidelike** [comment]
> Me changing this is pending on if ctrl-` works on Windows, in which case we can have a single default, otherwise I will set the default based on the platform. See [saidelike/cursorless#2](https://github.com/saidelike/cursorless/pull/2)

I would be tempted to keep different shortcuts for different platform as ctrl-shift-f12 is better for Windows so each platform has its own prefered one

**Comment by saidelike** [comment]
We might be able to not even set a default setting at all in talon and let the user set it only if needed?

**Comment by fidgetingbits** [comment]
Fixed now. I mix linux and mac shortcut for now, as I did that in cursorless.nvim as well. Can change it if/when it becomes an issue to actually separate, but I think it should be ok for now.

> I would set the default setting in neovim-talon based on platform

**Review by saidelike — APPROVED** [review]

**Pull request merged**
